-   id: add-2trailing-commas
    name: Add 2 trailing commas
    description: Automatically add 2 trailing commas to calls and literals.
    entry: add-2trailing-commas
    language: python
    types: [python]
